account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='account/signin.html'), name='signin'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/signin.html' ,extra_context={'logoutMess':"You're now logged out"}), name='logout'),
    path('delete/<int:p_id>', views.delete, name='delete_product'),

]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:p_id>', views.edit, name='edit_product'),
    path('detail/<int:product_id>', views.detail, name='detail'),
    path('upvote/<int:product_id>', views.upvote, name='upvote'),
]

producthunt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from product import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('product/', include('product.urls', namespace='product')),
    path('accounts/', include('account.urls', namespace='account'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Product(models.Model):
    title = models.CharField(max_length=50)
    pub_date = models.DateTimeField(default=timezone.now)
    icon = models.ImageField(upload_to='images/')
    image = models.ImageField(upload_to='images/')
    votes = models.IntegerField(default=0)
    body = models.TextField()
    product_url = models.CharField(max_length=100)
    hunter = models.ForeignKey(User, on_delete=models.CASCADE)

    def summary(self):
        return self.body[:100]

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e, %Y')

    def __str__(self):
        return self.title


class Voter(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

product/forms.py
from django import forms
from .models import Product



class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'
        exclude = ['pub_date']
    
    
        

product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Product, Voter
from .forms import ProductForm


def index(request):
    products = Product.objects.order_by('-votes')

    return render(request, 'product/index.html', {'products': products})


@login_required
def add_product(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['body'] and request.POST['url'] and request.FILES['icon'] and request.FILES['image']:
            product = Product()
            product.title = request.POST['title']
            product.body = request.POST['body']
            product.product_url = request.POST['url']
            product.icon = request.FILES['icon']
            product.image = request.FILES['image']
            product.hunter = request.user
            product.save()

            return redirect('/product/detail/'+str(product.id))
        else:
            messages.error(request, 'Please input all fields')
            return render(request, 'product/add.html')
    else:
        return render(request, 'product/add.html')


def detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'product/detail.html', {'product': product})


@login_required
def upvote(request, product_id):
    if request.method == 'POST':
        if Voter.objects.filter(user=request.user.id, product=product_id).exists():
            return redirect('/product/detail/'+str(product_id))
        else:
            product = get_object_or_404(Product, pk=product_id)
            product.votes += 1
            product.save()
            voter_count = Voter(product=product, user=request.user)
            voter_count.save()
            return redirect('/product/detail/'+str(product.id))

    return redirect('/product/detail/'+str(product_id))


@login_required
def edit(request, p_id):
    product = get_object_or_404(Product, pk=p_id) 
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, isinstance=product)
        if form.is_valid :
            ProductTitle = form.cleaned_data['title']
            form.save
            messages.success(request,ProductTitle+" Successfully edited ")
            return redirect('account:index')
    else:
         # user wants to edit a product
        form = ProductForm(instance=Product)
        return render(request, 'product/edit.html',{"form":form,"IdProduct":p_id})
'''def edit(request,p_id):
    product = get_object_or_404(Product, pk=p_id)
    if request.method == 'POST':
        if request.POST['title'] and request.POST['body'] and request.POST['url']:
            product.title = request.POST['title']
            product.body = request.POST['body']
            product.product_url = request.POST['url']
            if 'icon' in request.FILES :
                product.icon = request.FILES['icon']
            if 'image' in request.FILES :    
                product.image = request.FILES['image']
            product.hunter = request.user
            product.save()

            messages.success(request,product.title+" Successfully edited ")
            return redirect('/accounts/')
        else:
            messages.error(request,'Please input all fields')
            return render(request, 'product/edit.html')
    else:
        # user wants to edit a product
        return render(request, 'product/edit.html',{"product":product})
'''

product/templates/base.html
{% load static %}
<!Doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">

    <title>{% block title %}{% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'external/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'external/fontawesome/css/font-awesome.min.css' %}">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>

</head>

<body>
    <header>
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{% url 'product:index' %}"><i class="fa fa-product-hunt"
                        style="color:goldenrod; font-size: 27px;"></i>
                    Product Hunt</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" id=Homepage href="{% url 'product:index' %}"><i class="fa fa-home"></i>
                                Homepage</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id=MyProducts href="{% url 'account:index' %}"><i
                                    class="fa fa-list-ul"></i>
                                My products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id=AddProduct href="{% url 'product:add_product' %}"><i
                                    class="fa fa-plus"></i>
                                add product</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" id=Logout
                                href="javascript:{document.getElementById('logout').submit()}"><i
                                    class="fa fa-sign-in"></i>
                                Logout</a>
                            <form action="{% url 'account:logout' %}" method="POST" id="logout">{% csrf_token %}
                                <input type="hidden">
                            </form>
                        </li>

                        {% else %}

                        <li class="nav-item">
                            <a class="nav-link" id=SignUp href="{% url 'account:signup' %}"><i
                                    class="fa fa-user-plus"></i>
                                Sign Up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id=Login href="{% url 'account:signin' %}"><i class="fa fa-user"></i></i>
                                Login</a>
                        </li>
                        {% endif %}

                    </ul>
                </div>
            </nav>
        </div>
    </header>

    <main role="main">


        {% block content %}

        {% endblock content %}

    </main>

    <footer class="text-muted">
        <div class="container text-center">
            <p>&copy; ProductHunt {% now 'Y' %}</p>
        </div>
    </footer>
    <script src="{% static 'external/js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'external/js/popper.min.js' %}"></script>
    <script src="{% static 'external/js/bootstrap.min.js'%}"></script>
    <script>
        $(document).ready(function () {
            var title = document.title;
            switch (title) {
                case 'Home-Product Hunt':
                    $('#Homepage').addClass("active");
                    break;

                case 'User-Home':
                    $('#MyProducts').addClass("active");
                    break;

                case 'Add product':
                    $('#AddProduct').addClass("active");
                    break;

                case 'User Registration':
                    $('#SignUp').addClass("active");
                    break;

                case 'User Login':
                    $('#Login').addClass("active");
                    break;
            }


        }
        );
    </script>
</body>

</html>