account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='account/signin.html'), name='signin'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/signin.html' ,extra_context={'logoutMess':"You're now logged out"}), name='logout'),
    path('delete/<int:p_id>', views.delete, name='delete_product'),

]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:p_id>', views.edit, name='edit_product'),
    path('detail/<int:product_id>', views.detail, name='detail'),
    path('upvote/<int:product_id>', views.upvote, name='upvote'),
]

producthunt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from product import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('product/', include('product.urls', namespace='product')),
    path('accounts/', include('account.urls', namespace='account'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Product(models.Model):
    title = models.CharField(max_length=50)
    pub_date = models.DateTimeField(default=timezone.now)
    icon = models.ImageField(upload_to='images/')
    image = models.ImageField(upload_to='images/')
    votes = models.IntegerField(default=0)
    body = models.TextField()
    product_url = models.CharField(max_length=100)
    hunter = models.ForeignKey(User, on_delete=models.CASCADE)

    def summary(self):
        return self.body[:100]

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e, %Y')

    def __str__(self):
        return self.title


class Voter(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

product/forms.py
from django import forms
from .models import Product



class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'
        exclude = ['pub_date']
    
    
        

product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Product, Voter
from .forms import ProductForm


def index(request):
    products = Product.objects.order_by('-votes')

    return render(request, 'product/index.html', {'products': products})


@login_required
def add_product(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['body'] and request.POST['url'] and request.FILES['icon'] and request.FILES['image']:
            product = Product()
            product.title = request.POST['title']
            product.body = request.POST['body']
            product.product_url = request.POST['url']
            product.icon = request.FILES['icon']
            product.image = request.FILES['image']
            product.hunter = request.user
            product.save()

            return redirect('/product/detail/'+str(product.id))
        else:
            messages.error(request, 'Please input all fields')
            return render(request, 'product/add.html')
    else:
        return render(request, 'product/add.html')


def detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'product/detail.html', {'product': product})


@login_required
def upvote(request, product_id):
    if request.method == 'POST':
        if Voter.objects.filter(user=request.user.id, product=product_id).exists():
            return redirect('/product/detail/'+str(product_id))
        else:
            product = get_object_or_404(Product, pk=product_id)
            product.votes += 1
            product.save()
            voter_count = Voter(product=product, user=request.user)
            voter_count.save()
            return redirect('/product/detail/'+str(product.id))

    return redirect('/product/detail/'+str(product_id))


@login_required
def edit(request, p_id):
    product = get_object_or_404(Product, pk=p_id) 
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, isinstance=product)
        if form.is_valid :
            ProductTitle = form.cleaned_data['title']
            form.save
            messages.success(request,ProductTitle+" Successfully edited ")
            return redirect('account:index')
    else:
         # user wants to edit a product
        form = ProductForm(instance=Product)
        return render(request, 'product/edit.html',{"form":form,"IdProduct":p_id})
'''def edit(request,p_id):
    product = get_object_or_404(Product, pk=p_id)
    if request.method == 'POST':
        if request.POST['title'] and request.POST['body'] and request.POST['url']:
            product.title = request.POST['title']
            product.body = request.POST['body']
            product.product_url = request.POST['url']
            if 'icon' in request.FILES :
                product.icon = request.FILES['icon']
            if 'image' in request.FILES :    
                product.image = request.FILES['image']
            product.hunter = request.user
            product.save()

            messages.success(request,product.title+" Successfully edited ")
            return redirect('/accounts/')
        else:
            messages.error(request,'Please input all fields')
            return render(request, 'product/edit.html')
    else:
        # user wants to edit a product
        return render(request, 'product/edit.html',{"product":product})
'''

product/templates/product/add.html
{% extends 'base.html' %}

{% block title %}Add product{% endblock title %}

{% block content %}
<br><br>
<div class="container">
    <div class="row">
        <div class="container col-md-6">
            <h4>Add Product</h4>
            <hr>
            <pre class="bg-warning">{{ error_message }}</pre>
            <form action="{% url 'product:add_product' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" name="title" placeholder="Enter title" required>
                </div>
                <div class="form-group">
                    <label for="body">Description</label>
                    <textarea class="form-control" id="body" name="body" rows="3" required></textarea>
                </div>
                <div class="form-group">
                    <label for="url">Product url</label>
                    <input type="text" class="form-control" id="url" name="url" placeholder="Enter product url"
                        required>
                </div>
                <div class="form-group">
                    <label for="icon">Product icon</label>
                    <input type="file" class="form-control-file" id="icon" name="icon">
                </div>
                <div class="form-group">
                    <label for="icon">Product image</label>
                    <input type="file" class="form-control-file" id="image" name="image">
                </div>
                <button type="submit" class="btn btn-primary">Upload</button>
            </form>
        </div>
    </div>
</div>
<br><br><br><br>
{% endblock content %}

product/templates/product/detail.html
{% extends 'base.html' %}

{% block title %}Product Details{% endblock title %}

{% block content %}
<br><br><br>
<div class="container">
    <div class="row">
        <div class="col-2">
            <img src="{{ product.icon.url }}" class="img-fluid" />
        </div>

        <div class="col-10">
            <h1>{{ product.title }}</h1>
        </div>
    </div>
    <br />

    <div class="row">
        <div class="col-8">
            <img src="{{ product.image.url }}" class="img-fluid" />
        </div>

        <div class="col-4">
            <form action="{% url 'product:upvote' product.id %} " method="POST" id='upvote'>
                {% csrf_token %}
                <button class="btn btn-primary btn-lg btn-block"><i class="fa fa-caret-up">
                    </i> Upvote {{ product.votes }} </button>
                <input type="hidden" name='vote'>
            </form>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-4">
            <h4><i class="fa fa-search"></i> Hunted by {{ product.hunter.username }}</h4>
        </div>

        <div class="col-4 text-right">
            <h4><i class="far fa-clock"></i> {{ product.pub_date_pretty }}</h4>
        </div>

    </div>
    <br />
    <div class="row">

        <div class="col-8">
            <p> {{ product.body }}</p>
        </div>

    </div>
</div>
<form action=" {% url 'product:upvote' product.id %} " method="POST" id='upvote'>
    {% csrf_token %}
    <input type="hidden" name='vote'>
</form>

{% endblock %}

product/templates/product/edit.html
{% extends 'base.html' %}

{% block title %}Edit product{% endblock title %}

{% block content %}
<br><br>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h4>Edit Product</h4>
            <hr>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}

            <form action="{% url 'product:edit_product' IdProduct %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
               
                <div class="form-group">
                    <label for="title">Title</label>
                    {{form.title}}
                </div>
                <div class="form-group">
                    <label for="body">Description</label>
                    <textarea class="form-control" id="body" name="body" rows="3" required>{{form.body}}</textarea>
                </div>
                <div class="form-group">
                    <label for="url">Product url</label>
                    <input type="text" class="form-control" id="url" name="url" value="{{form.product_url}}"
                        required>
                </div>
                <div class="form-group">
                    <label for="icon">Product icon</label> <br>
                    <img class="img img-fluid" src="{{form.icon.url}}">
                    <input type="file" class="form-control-file" id="icon" name="icon" value="{{form.icon.url}}">
                </div>
                <div class="form-group">
                    <label for="icon">Product image</label> <br>
                    <img class="img img-fluid" src="{{form.image.url}}">
                    <input type="file" class="form-control-file" id="image" name="image" value="{{form.image.url}}">
                </div>
                <button type="submit" class="btn btn-primary">Upload</button>
                <a for=button class="btn btn-danger" href="{% url 'account:index'  %}">Cancel</a>
            </form>
        </div>
    </div>
</div>
<br><br><br><br>
{% endblock content %}

product/templates/product/index.html
{% extends 'base.html' %}
{% block title %}Home-Product Hunt{% endblock title %}


{% block content %}
<div class="container">
    <br>
    {% for product in products %}
    <div class="row pt-5">
        <div class="col-md-2">
            <img src="{{ product.icon.url }}" class="img-fluid" />
        </div>
        <div class="col-md-7">
            <a href="{% url 'product:detail' product.id %}">
                <h2>{{ product.title }}</h2>
            </a>
            <p>{{ product.summary }}</p>
        </div>
        <div class="col-md-3">
            <form action="{% url 'product:upvote' product.id %} " method="POST" id='upvote'>
                {% csrf_token %}
                <button class="btn btn-primary btn-lg btn-block"><i class="fa fa-caret-up">
                    </i> Upvote {{ product.votes }} </button>
                <input type="hidden" name='vote'>
            </form>
        </div>
    </div>
    {% endfor %}
</div>
<div class="pb-5"></div>
{% endblock content %}